/**
 * @file bandpass_coefficients_48k.hpp
 * @brief Pre-computed 1/3 octave bandpass filter coefficients for 48kHz
 *
 * Auto-generated by tools/regen_bandpass_coefficients.py (v3.3.1).
 * Each band is a 2nd-order Butterworth bandpass (single biquad section).
 * Coefficients are normalized (a0 = 1.0) and peak-gain compensated
 * via peak_gain_correction[].
 *
 * v3.3.1 (2026-09-09): scipy.signal.butter(1, ..., btype='band', fs=48000)
 *   - 替代 v3.3.0 的简化公式（6 行手写 bilinear）
 *   - |H(fc)| 实测 ≈ 1.0（v3.3.0 是 5e-6）
 *   - peak_gain_correction ≈ 1.0（v3.3.0 是 ~2e5）
 *   - b0 数量级从 1e-7 升到 1e-2（float32 精度更优）
 *
 * Design invariants:
 *   - scipy zpk → lp2bp → bilinear pipeline (not simplified formula)
 *   - peak_gain_correction = 1/|H(fc)| (always exactly 1.0 for scipy design)
 *   - biquad poles stay inside unit circle in float32 (stable)
 */

#pragma once

#include <cstdint>

namespace noise_toolkit {

struct BandpassCoeffs {
    float b0, b1, b2, a1, a2;  // a0 = 1.0 (normalized)
    float peak_gain_correction;  // 1.0 / |H(fc)|, applied at SPL level
};

constexpr BandpassCoeffs BANDPASS_COEFFS_48K[9] = {
    // Band 0: 63 Hz (56.1 - 70.7 Hz), peak_gain=1.000000e+00, correction=1.000000e+00
    { 9.5390391335e-04f, 0.0000000000e+00f, -9.5390391335e-04f, -1.9980242497e+00f, 9.9809219217e-01f, 1.0000000000e+00f },
    // Band 1: 125 Hz (111.4 - 140.3 Hz), peak_gain=1.000000e+00, correction=1.000000e+00
    { 1.8908930810e-03f, 0.0000000000e+00f, -1.8908930810e-03f, -1.9959509956e+00f, 9.9621821384e-01f, 1.0000000000e+00f },
    // Band 2: 250 Hz (222.7 - 280.6 Hz), peak_gain=1.000000e+00, correction=1.000000e+00
    { 3.7746622011e-03f, 0.0000000000e+00f, -3.7746622011e-03f, -1.9913838874e+00f, 9.9245067560e-01f, 1.0000000002e+00f },
    // Band 3: 500 Hz (445.4 - 561.2 Hz), peak_gain=1.000000e+00, correction=1.000000e+00
    { 7.5210425735e-03f, 0.0000000000e+00f, -7.5210425735e-03f, -1.9807078862e+00f, 9.8495791485e-01f, 1.0000000034e+00f },
    // Band 4: 1000 Hz (890.9 - 1122.5 Hz), peak_gain=9.999999e-01, correction=1.000000e+00
    { 1.4930642120e-02f, 0.0000000000e+00f, -1.4930642120e-02f, -1.9532826157e+00f, 9.7013871576e-01f, 1.0000000548e+00f },
    // Band 5: 2000 Hz (1781.8 - 2244.9 Hz), peak_gain=9.999991e-01, correction=1.000001e+00
    { 2.9428556760e-02f, 0.0000000000e+00f, -2.9428556760e-02f, -1.8749798052e+00f, 9.4114288648e-01f, 1.0000008828e+00f },
    // Band 6: 4000 Hz (3563.6 - 4489.8 Hz), peak_gain=9.999855e-01, correction=1.000015e+00
    { 5.7224150414e-02f, 0.0000000000e+00f, -5.7224150414e-02f, -1.6326271778e+00f, 8.8555169917e-01f, 1.0000145312e+00f },
    // Band 7: 8000 Hz (7127.2 - 8979.7 Hz), peak_gain=9.997376e-01, correction=1.000262e+00
    { 1.0861040606e-01f, 0.0000000000e+00f, -1.0861040606e-01f, -8.8707935581e-01f, 7.8277918789e-01f, 1.0002624529e+00f },
    // Band 8: 16000 Hz (14254.4 - 17959.4 Hz), peak_gain=9.918602e-01, correction=1.008207e+00
    { 1.9830691563e-01f, 0.0000000000e+00f, -1.9830691563e-01f, 8.4578766884e-01f, 6.0338616874e-01f, 1.0082066354e+00f },
};

} // namespace noise_toolkit
