/**
 * @file bandpass_coefficients_48k.hpp
 * @brief Pre-computed 1/3 octave bandpass filter coefficients for 48kHz
 *
 * Auto-generated by tools/generate_bandpass_coeffs.cpp
 * Each band is a 2nd-order Butterworth bandpass (single biquad section).
 * Coefficients are normalized (a0 = 1.0).
 */

#pragma once

namespace noise_toolkit {

struct BandpassCoeffs {
    float b0, b1, b2, a1, a2;  // a0 = 1.0 (normalized)
};

constexpr BandpassCoeffs BANDPASS_COEFFS_48K[9] = {
    // Band 0: 63 Hz (56.1 - 70.7 Hz)
    { 1.9891967185e-08f, 0.0000000000e+00f, -1.9891967185e-08f, -2.0000000000e+00f, 9.9999994040e-01f },
    // Band 1: 125 Hz (111.4 - 140.3 Hz)
    { 3.9468183388e-08f, 0.0000000000e+00f, -3.9468183388e-08f, -1.9999998808e+00f, 9.9999994040e-01f },
    // Band 2: 250 Hz (222.7 - 280.6 Hz)
    { 7.8936359671e-08f, 0.0000000000e+00f, -7.8936359671e-08f, -1.9999998808e+00f, 9.9999982119e-01f },
    // Band 3: 500 Hz (445.4 - 561.2 Hz)
    { 1.5787270513e-07f, 0.0000000000e+00f, -1.5787270513e-07f, -1.9999996424e+00f, 9.9999970198e-01f },
    // Band 4: 1000 Hz (890.9 - 1122.5 Hz)
    { 3.1574538184e-07f, 0.0000000000e+00f, -3.1574538184e-07f, -1.9999994040e+00f, 9.9999934435e-01f },
    // Band 5: 2000 Hz (1781.8 - 2244.9 Hz)
    { 6.3149053631e-07f, 0.0000000000e+00f, -6.3149053631e-07f, -1.9999986887e+00f, 9.9999874830e-01f },
    // Band 6: 4000 Hz (3563.6 - 4489.8 Hz)
    { 1.2629802768e-06f, 0.0000000000e+00f, -1.2629802768e-06f, -1.9999974966e+00f, 9.9999749660e-01f },
    // Band 7: 8000 Hz (7127.2 - 8979.7 Hz)
    { 2.5259573704e-06f, 0.0000000000e+00f, -2.5259573704e-06f, -1.9999949932e+00f, 9.9999493361e-01f },
    // Band 8: 16000 Hz (14254.4 - 17959.4 Hz)
    { 5.0519020078e-06f, 0.0000000000e+00f, -5.0519020078e-06f, -1.9999898672e+00f, 9.9998986721e-01f }
};

} // namespace noise_toolkit
