/**
 * @file bandpass_coefficients_48k.hpp
 * @brief Pre-computed 1/3 octave bandpass filter coefficients for 48kHz
 *
 * Auto-generated by tools/generate_bandpass_coeffs.cpp
 * Each band is a 2nd-order Butterworth bandpass (single biquad section).
 * Coefficients are normalized (a0 = 1.0).
 *
 * v3.2: peak_gain_correction[] is applied at the SPL output level
 *       to compensate for b0 = wc/Q scaling (Bug A fix). Do NOT
 *       bake the correction into b0 directly: that would amplify
 *       b0 by 200000x and push the biquad poles (which sit very
 *       close to z=1 for high-Q 1/3 octave filters) outside the
 *       unit circle in float32, causing instability.
 */

#pragma once

namespace noise_toolkit {

struct BandpassCoeffs {
    float b0, b1, b2, a1, a2;  // a0 = 1.0 (normalized)
    float peak_gain_correction;  // 1.0 / |H(fc)|, applied at SPL level
};

constexpr BandpassCoeffs BANDPASS_COEFFS_48K[9] = {
    // Band 0: 63 Hz (56.1 - 70.7 Hz), peak_gain=4.820e-06, correction=2.075e+05
    { 1.9891967185e-08f, 0.0000000000e+00f, -1.9891967185e-08f, -2.0000000000e+00f, 9.9999994040e-01f, 2.0746954688e+05f },
    // Band 1: 125 Hz (111.4 - 140.3 Hz), peak_gain=4.825e-06, correction=2.072e+05
    { 3.9468183388e-08f, 0.0000000000e+00f, -3.9468183388e-08f, -1.9999998808e+00f, 9.9999994040e-01f, 2.0724520312e+05f },
    // Band 2: 250 Hz (222.7 - 280.6 Hz), peak_gain=4.824e-06, correction=2.073e+05
    { 7.8936359671e-08f, 0.0000000000e+00f, -7.8936359671e-08f, -1.9999998808e+00f, 9.9999982119e-01f, 2.0731678125e+05f },
    // Band 3: 500 Hz (445.4 - 561.2 Hz), peak_gain=4.823e-06, correction=2.074e+05
    { 1.5787270513e-07f, 0.0000000000e+00f, -1.5787270513e-07f, -1.9999996424e+00f, 9.9999970198e-01f, 2.0735787500e+05f },
    // Band 4: 1000 Hz (890.9 - 1122.5 Hz), peak_gain=4.817e-06, correction=2.076e+05
    { 3.1574538184e-07f, 0.0000000000e+00f, -3.1574538184e-07f, -1.9999994040e+00f, 9.9999934435e-01f, 2.0758393750e+05f },
    // Band 5: 2000 Hz (1781.8 - 2244.9 Hz), peak_gain=4.797e-06, correction=2.085e+05
    { 6.3149053631e-07f, 0.0000000000e+00f, -6.3149053631e-07f, -1.9999986887e+00f, 9.9999874830e-01f, 2.0847865625e+05f },
    // Band 6: 4000 Hz (3563.6 - 4489.8 Hz), peak_gain=4.714e-06, correction=2.122e+05
    { 1.2629802768e-06f, 0.0000000000e+00f, -1.2629802768e-06f, -1.9999974966e+00f, 9.9999749660e-01f, 2.1215601562e+05f },
    // Band 7: 8000 Hz (7127.2 - 8979.7 Hz), peak_gain=4.375e-06, correction=2.286e+05
    { 2.5259573704e-06f, 0.0000000000e+00f, -2.5259573704e-06f, -1.9999949932e+00f, 9.9999493361e-01f, 2.2856634375e+05f },
    // Band 8: 16000 Hz (14254.4 - 17959.4 Hz), peak_gain=2.917e-06, correction=3.428e+05
    { 5.0519020078e-06f, 0.0000000000e+00f, -5.0519020078e-06f, -1.9999898672e+00f, 9.9998986721e-01f, 3.4284950000e+05f }
};

} // namespace noise_toolkit
