/**
 * @file weighting_coefficients_matched_z_48k.hpp
 * @brief Matched-z A/C weighting for fs=48000 (v3.3.0)
 *
 * DESIGN: Matched-z transform + 2nd-order parametric correction
 *   Stage 1: z_p = exp(s_p·T) — pole positions EXACT
 *   Stage 2: 2nd-order RBJ peaking EQ — corrects HF gain shape
 * Post-chain: 1 kHz gain normalization factor applied ONCE
 *
 * TARGET: IEC 61672-1 Class 1 (±0.7 dB)
 * Generated by tools/regen_weighting_matched_z.py
 */
#pragma once
namespace noise_toolkit_mz {
struct Wt { float b0,b1,b2,a1,a2; };
struct Chain { const Wt* s; int n; float g; };

static constexpr WeightingCoeffs A_48000[4] = {
    { 1.0000000000e+00f, 0.0000000000e+00f, 0.0000000000e+00f, -4.0532255690e-01f, 4.1071593782e-02f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.8939389909e+00f, 8.9522728880e-01f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9946144593e+00f, 9.9462171026e-01f },
    { 8.1132789931e-01f, 8.4654422750e-01f, 1.6617728679e-01f, 8.4654422750e-01f, -2.2494813895e-02f },
};

static constexpr WeightingCoeffs C_48000[3] = {
    { 1.0000000000e+00f, 0.0000000000e+00f, 0.0000000000e+00f, -4.0532255690e-01f, 4.1071593782e-02f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9946144593e+00f, 9.9462171026e-01f },
    { 7.6934565533e-01f, -2.5710081969e-01f, 0.0000000000e+00f, -1.9553572705e-01f, 0.0000000000e+00f },
};

static constexpr Chain A_CHAIN = { A_48000, 4, 7.5577396405e-01f };
static constexpr Chain C_CHAIN = { C_48000, 3, 9.9776330403e-01f };
} // namespace
