/**
 * @file weighting_coefficients_multirate.hpp
 * @brief Pre-computed A/C weighting coefficients for 7 sample rates (v3.2.1)
 *
 * v3.2.1 BUG FIX: Gain normalization is now a SEPARATE FACTOR (a_gain / c_gain)
 * applied AFTER the biquad chain. Previous v3.2 implementation multiplied
 * only sos[0].b by 1/H_total(1kHz), which distorted the frequency response
 * at high frequencies (10 kHz should be -82 dB but was +16 to +45 dB).
 *
 * Regenerated by tools/regen_weighting_coefficients.py from scipy.signal.bilinear
 * with IEC 61672-1 Class 1 reference response.
 */
#pragma once
namespace noise_toolkit {
struct WeightingCoeffs { float b0, b1, b2, a1, a2; };
struct WeightingTableEntry {
    const WeightingCoeffs* a;
    int a_count;
    float a_gain;          // 1kHz normalization factor: multiply chain output by this
    const WeightingCoeffs* c;
    int c_count;
    float c_gain;          // 1kHz normalization factor for C
};

static constexpr WeightingCoeffs A_8000[3] = {
    { 8.5332764823e-11f, 1.7066552965e-10f, 8.5332764823e-11f, 1.0381804979e-01f, -3.6041743816e-01f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -2.6438243082e-01f, -6.0140346174e-01f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9679028120e+00f, 9.6816036935e-01f },
};

static constexpr WeightingCoeffs C_8000[2] = {
    { 1.1471133874e-10f, 2.2942267749e-10f, 1.1471133874e-10f, 1.3089935308e+00f, 4.2836601594e-01f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9679028120e+00f, 9.6816036935e-01f },
};

static constexpr WeightingCoeffs A_16000[3] = {
    { 7.1918791919e-11f, 1.4383758384e-10f, 7.1918791919e-11f, 8.2156381798e-01f, 1.6874177675e-01f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.7055096337e+00f, 7.1598757535e-01f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9838867573e+00f, 9.8395166642e-01f },
};

static constexpr WeightingCoeffs C_16000[2] = {
    { 8.4078738078e-11f, 1.6815747616e-10f, 8.4078738078e-11f, 8.2156381798e-01f, 1.6874177675e-01f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9838867573e+00f, 9.8395166642e-01f },
};

static constexpr WeightingCoeffs A_22050[3] = {
    { 6.0797216878e-11f, 1.2159443376e-10f, 6.0797216878e-11f, 5.3874954260e-01f, 7.2562767413e-02f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.7795334341e+00f, 7.8528147097e-01f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9882949138e+00f, 9.8832916602e-01f },
};

static constexpr WeightingCoeffs C_22050[2] = {
    { 6.8219213056e-11f, 1.3643842611e-10f, 6.8219213056e-11f, 5.3874954260e-01f, 7.2562767413e-02f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9882949138e+00f, 9.8832916602e-01f },
};

static constexpr WeightingCoeffs A_32000[3] = {
    { 4.6475223808e-11f, 9.2950447615e-11f, 4.6475223808e-11f, 1.7947173147e-01f, 8.0525255991e-03f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.8439906561e+00f, 8.4681632406e-01f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9919271186e+00f, 9.9194341145e-01f },
};

static constexpr WeightingCoeffs C_32000[2] = {
    { 5.0368631096e-11f, 1.0073726219e-10f, 5.0368631096e-11f, 1.7947173147e-01f, 8.0525255991e-03f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9919271186e+00f, 9.9194341145e-01f },
};

static constexpr WeightingCoeffs A_44100[3] = {
    { 3.4605728532e-11f, 6.9211457065e-11f, 3.4605728532e-11f, -1.4053608242e-01f, 4.9375976155e-03f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.8849012174e+00f, 8.8642147182e-01f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9941388813e+00f, 9.9414746944e-01f },
};

static constexpr WeightingCoeffs C_44100[2] = {
    { 3.6704075874e-11f, 7.3408151747e-11f, 3.6704075874e-11f, -1.4053608242e-01f, 4.9375976155e-03f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9941388813e+00f, 9.9414746944e-01f },
};

static constexpr WeightingCoeffs A_48000[3] = {
    { 3.1704655294e-11f, 6.3409310587e-11f, 3.1704655294e-11f, -2.2455845806e-01f, 1.2606625272e-02f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.8938704947e+00f, 8.9515976909e-01f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9946144560e+00f, 9.9462170701e-01f },
};

static constexpr WeightingCoeffs C_48000[2] = {
    { 3.3469941474e-11f, 6.6939882949e-11f, 3.3469941474e-11f, -2.2455845806e-01f, 1.2606625272e-02f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9946144560e+00f, 9.9462170701e-01f },
};

static constexpr WeightingCoeffs A_96000[3] = {
    { 1.3466458086e-11f, 2.6932916172e-11f, 1.3466458086e-11f, -8.5907310284e-01f, 1.8450164900e-01f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9458245274e+00f, 9.4615560352e-01f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9973054140e+00f, 9.9730722922e-01f },
};

static constexpr WeightingCoeffs C_96000[2] = {
    { 1.3840212574e-11f, 2.7680425148e-11f, 1.3840212574e-11f, -8.5907310284e-01f, 1.8450164900e-01f },
    { 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.9973054140e+00f, 9.9730722922e-01f },
};

static constexpr WeightingTableEntry WEIGHTING_TABLE[7] = {
    { A_8000, 3, 7.2580413303e+09f, C_8000, 2, 5.9165766742e+09f },
    { A_16000, 3, 7.3568084245e+09f, C_16000, 2, 5.9133580011e+09f },
    { A_22050, 3, 7.3725496041e+09f, C_22050, 2, 5.9128913037e+09f },
    { A_32000, 3, 7.3817613369e+09f, C_32000, 2, 5.9126235472e+09f },
    { A_44100, 3, 7.3857084135e+09f, C_44100, 2, 5.9125100018e+09f },
    { A_48000, 3, 7.3863929582e+09f, C_48000, 2, 5.9124903810e+09f },
    { A_96000, 3, 7.3891735109e+09f, C_96000, 2, 5.9124108996e+09f },
};

/** Look up weighting table entry by sample rate (returns nullptr if not found) */
static constexpr const WeightingTableEntry* find_weighting_entry(int sample_rate) {
    switch (sample_rate) {
    case 8000: return &WEIGHTING_TABLE[0];
    case 16000: return &WEIGHTING_TABLE[1];
    case 22050: return &WEIGHTING_TABLE[2];
    case 32000: return &WEIGHTING_TABLE[3];
    case 44100: return &WEIGHTING_TABLE[4];
    case 48000: return &WEIGHTING_TABLE[5];
    case 96000: return &WEIGHTING_TABLE[6];
    default: return nullptr;
    }
}
} // namespace
