/**
 * @file generate_bandpass_coeffs.cpp
 * @brief Generate pre-computed bandpass filter coefficients for 48kHz
 *
 * v3.2: Output BOTH the original (un-normalized) biquad coefficients AND
 *       a per-band peak-gain correction factor. The SPL calculation in
 *       noise_processor.cpp applies the correction to the RMS before
 *       converting to dB, which gives physically correct band SPL output
 *       without changing the (potentially marginally-stable) biquad design.
 *
 * Build & run:
 *   g++ -std=c++17 -I../include -o gen_bp ../src/iir_filter.cpp generate_bandpass_coeffs.cpp
 *   ./gen_bp > ../include/bandpass_coefficients_48k.hpp
 */

#include "iir_filter.hpp"
#include <cstdio>
#include <cmath>
#include <complex>

using namespace noise_toolkit;

int main() {
    constexpr float SAMPLE_RATE = 48000.0f;
    constexpr double PI = 3.14159265358979323846;
    constexpr float BAND_FACTOR = 1.12246204830937f; // 2^(1/6)
    constexpr float BAND_CENTER_FREQS[9] = {
        63.0f, 125.0f, 250.0f, 500.0f, 1000.0f,
        2000.0f, 4000.0f, 8000.0f, 16000.0f
    };

    printf("/**\n");
    printf(" * @file bandpass_coefficients_48k.hpp\n");
    printf(" * @brief Pre-computed 1/3 octave bandpass filter coefficients for 48kHz\n");
    printf(" *\n");
    printf(" * Auto-generated by tools/generate_bandpass_coeffs.cpp\n");
    printf(" * Each band is a 2nd-order Butterworth bandpass (single biquad section).\n");
    printf(" * Coefficients are normalized (a0 = 1.0).\n");
    printf(" *\n");
    printf(" * v3.2: peak_gain_correction[] is applied at the SPL output level\n");
    printf(" *       to compensate for b0 = wc/Q scaling (Bug A fix). Do NOT\n");
    printf(" *       bake the correction into b0 directly: that would amplify\n");
    printf(" *       b0 by 200000x and push the biquad poles (which sit very\n");
    printf(" *       close to z=1 for high-Q 1/3 octave filters) outside the\n");
    printf(" *       unit circle in float32, causing instability.\n");
    printf(" */\n\n");
    printf("#pragma once\n\n");
    printf("namespace noise_toolkit {\n\n");
    printf("struct BandpassCoeffs {\n");
    printf("    float b0, b1, b2, a1, a2;  // a0 = 1.0 (normalized)\n");
    printf("    float peak_gain_correction;  // 1.0 / |H(fc)|, applied at SPL level\n");
    printf("};\n\n");
    printf("constexpr BandpassCoeffs BANDPASS_COEFFS_48K[9] = {\n");

    for (int i = 0; i < 9; ++i) {
        float fc = BAND_CENTER_FREQS[i];
        float fc_low = fc / BAND_FACTOR;
        float fc_high = fc * BAND_FACTOR;

        auto coef = filter_design::bandpass(fc_low, fc_high, SAMPLE_RATE, 2);

        // Compute peak gain |H(z=e^jω0)| using double precision
        double w0 = 2.0 * PI * fc / SAMPLE_RATE;
        std::complex<double> z_inv = std::polar(1.0, -w0);
        std::complex<double> z_inv2 = z_inv * z_inv;
        double num_re = static_cast<double>(coef.b[0])
                      + static_cast<double>(coef.b[1]) * z_inv.real()
                      + static_cast<double>(coef.b[2]) * z_inv2.real();
        double num_im = static_cast<double>(coef.b[1]) * z_inv.imag()
                      + static_cast<double>(coef.b[2]) * z_inv2.imag();
        double den_re = static_cast<double>(coef.a[0])
                      + static_cast<double>(coef.a[1]) * z_inv.real()
                      + static_cast<double>(coef.a[2]) * z_inv2.real();
        double den_im = static_cast<double>(coef.a[1]) * z_inv.imag()
                      + static_cast<double>(coef.a[2]) * z_inv2.imag();
        double num_mag = std::sqrt(num_re * num_re + num_im * num_im);
        double den_mag = std::sqrt(den_re * den_re + den_im * den_im);
        double peak_gain = (den_mag > 1e-30) ? (num_mag / den_mag) : 1.0;
        float correction = (peak_gain > 1e-30) ? static_cast<float>(1.0 / peak_gain) : 1.0f;

        printf("    // Band %d: %.0f Hz (%.1f - %.1f Hz), peak_gain=%.3e, correction=%.3e\n",
               i, fc, fc_low, fc_high, peak_gain, correction);
        printf("    { %.10ef, %.10ef, %.10ef, %.10ef, %.10ef, %.10ef }%s\n",
               coef.b[0], coef.b[1], coef.b[2],
               coef.a[1], coef.a[2],
               correction,
               (i < 8) ? "," : "");
    }

    printf("};\n\n");
    printf("} // namespace noise_toolkit\n");

    return 0;
}
