/**
 * @file generate_bandpass_coeffs.cpp
 * @brief Generate pre-computed bandpass filter coefficients for 48kHz
 *
 * Build & run:
 *   g++ -std=c++17 -I../include -o gen_bp ../src/iir_filter.cpp generate_bandpass_coeffs.cpp
 *   ./gen_bp > ../include/bandpass_coefficients_48k.hpp
 */

#include "iir_filter.hpp"
#include <cstdio>
#include <cmath>

using namespace noise_toolkit;

int main() {
    constexpr float SAMPLE_RATE = 48000.0f;
    constexpr float BAND_FACTOR = 1.12246204830937f; // 2^(1/6)
    constexpr float BAND_CENTER_FREQS[9] = {
        63.0f, 125.0f, 250.0f, 500.0f, 1000.0f,
        2000.0f, 4000.0f, 8000.0f, 16000.0f
    };

    printf("/**\n");
    printf(" * @file bandpass_coefficients_48k.hpp\n");
    printf(" * @brief Pre-computed 1/3 octave bandpass filter coefficients for 48kHz\n");
    printf(" *\n");
    printf(" * Auto-generated by tools/generate_bandpass_coeffs.cpp\n");
    printf(" * Each band is a 2nd-order Butterworth bandpass (single biquad section).\n");
    printf(" * Coefficients are normalized (a0 = 1.0).\n");
    printf(" */\n");
    printf("\n#pragma once\n\n");
    printf("namespace noise_toolkit {\n\n");
    printf("struct BandpassCoeffs {\n");
    printf("    float b0, b1, b2, a1, a2;  // a0 = 1.0 (normalized)\n");
    printf("};\n\n");
    printf("constexpr BandpassCoeffs BANDPASS_COEFFS_48K[9] = {\n");

    for (int i = 0; i < 9; ++i) {
        float fc = BAND_CENTER_FREQS[i];
        float fc_low = fc / BAND_FACTOR;
        float fc_high = fc * BAND_FACTOR;

        auto coef = filter_design::bandpass(fc_low, fc_high, SAMPLE_RATE, 2);

        printf("    // Band %d: %.0f Hz (%.1f - %.1f Hz)\n", i, fc, fc_low, fc_high);
        printf("    { %.10ef, %.10ef, %.10ef, %.10ef, %.10ef }%s\n",
               coef.b[0], coef.b[1], coef.b[2],
               coef.a[1], coef.a[2],
               (i < 8) ? "," : "");
    }

    printf("};\n\n");
    printf("} // namespace noise_toolkit\n");

    return 0;
}
