#!/usr/bin/env python3
"""
regen_bandpass_coefficients.py — 一次性脚本：scipy 重生成 9 套 1/3 oct biquad b/a

v3.3.1 修复方案（方案 1）：
- 用 scipy.signal.butter(1, [fc_low, fc_high], btype='band', fs=48000) 标准设计
- 验证 |H(fc)| ≈ 1.0（scipy 内部归一化）
- 计算 peak_gain_correction = 1/|H(fc)|（应该 ≈ 1.0）
- 输出 C++ constexpr 数组 → 覆盖 include/bandpass_coefficients_48k.hpp

为什么 v3.3.0 的简化公式会有 bug:
- tools/generate_bandpass_coeffs.cpp 用的 6 行简化公式只对中心频率做了半带 pre-warp
- b/a 没有 scale 到让 |H(fc)| = 1.0（实际 |H(fc)| ≈ 5e-6 而不是 1.0）
- correction 数值基于"应该有的 |H|"，但实际 biquad 跑出来的 |H| 跟设计预期差 20000x
- correction 跟 b/a 不自洽 → SPL 端补偿过度 / 不足 → 频段读数全数爆雷

为什么 scipy 设计能修:
- scipy.signal.butter 走完整 zpk → lp2bp → bilinear pipeline
- 自动归一化到 peak gain = 1.0（fc 处）
- correction 数值跟 b/a 完全自洽
- b0 系数从 1e-7 量级升到 1e-2 量级 → float32 精度更优 → 浮点累加误差大幅降低

用法:
    python3 tools/regen_bandpass_coefficients.py
    python3 tools/regen_bandpass_coefficients.py --output /tmp/check.hpp  # 仅 stdout

输出文件会被覆盖，请先备份!
"""

import sys
import argparse
from pathlib import Path
import numpy as np
from scipy.signal import butter, freqz


# 1/3 oct 频段中心频率 (Hz) — IEC 61260 标准倍频段（基准 1kHz，10 段一组）
BAND_CENTER_FREQS = [
    63.0, 125.0, 250.0, 500.0, 1000.0,
    2000.0, 4000.0, 8000.0, 16000.0,
]

BAND_FACTOR = 2.0 ** (1.0 / 6.0)  # 1/3 oct 上下边频比 ≈ 1.12246204830937
SAMPLE_RATE = 48000.0

# 输出文件路径（默认）
HEADER_PATH = Path(__file__).parent.parent / "include" / "bandpass_coefficients_48k.hpp"


def generate_one_band(fc, fs=SAMPLE_RATE, band_factor=BAND_FACTOR):
    """生成单频段 b/a + peak_gain_correction"""
    fc_low = fc / band_factor
    fc_high = fc * band_factor

    # scipy 标准设计: 1 个 biquad, 2 阶 Butterworth 带通
    b, a = butter(1, [fc_low, fc_high], btype='band', fs=fs)

    # 归一化到 a0 = 1（scipy 已经默认 a0=1，这里保险起见再除一次）
    b = b / a[0]
    a = a / a[0]

    # 验证 |H(fc)| ≈ 1.0 (freqz 在 fs 给定时 worN 直接用 Hz)
    w, h = freqz(b, a, worN=[fc], fs=fs)
    peak_gain = float(abs(h[0]))
    correction = 1.0 / peak_gain  # 期望 ≈ 1.0

    return {
        'fc': fc,
        'b0': float(b[0]),
        'b1': float(b[1]),
        'b2': float(b[2]),
        'a0': float(a[0]),
        'a1': float(a[1]),
        'a2': float(a[2]),
        'peak_gain': peak_gain,
        'correction': correction,
    }


def emit_cpp_header(coeffs_list, output):
        """输出 C++ constexpr 数组头文件"""
        output.write("/**\n")
        output.write(" * @file bandpass_coefficients_48k.hpp\n")
        output.write(" * @brief Pre-computed 1/3 octave bandpass filter coefficients for 48kHz\n")
        output.write(" *\n")
        output.write(" * Auto-generated by tools/regen_bandpass_coefficients.py (v3.3.1).\n")
        output.write(" * Each band is a 2nd-order Butterworth bandpass (single biquad section).\n")
        output.write(" * Coefficients are normalized (a0 = 1.0) and peak-gain compensated\n")
        output.write(" * via peak_gain_correction[].\n")
        output.write(" *\n")
        output.write(" * v3.3.1 (2026-09-09): scipy.signal.butter(1, ..., btype='band', fs=48000)\n")
        output.write(" *   - 替代 v3.3.0 的简化公式（6 行手写 bilinear）\n")
        output.write(" *   - |H(fc)| 实测 ≈ 1.0（v3.3.0 是 5e-6）\n")
        output.write(" *   - peak_gain_correction ≈ 1.0（v3.3.0 是 ~2e5）\n")
        output.write(" *   - b0 数量级从 1e-7 升到 1e-2（float32 精度更优）\n")
        output.write(" *\n")
        output.write(" * Design invariants:\n")
        output.write(" *   - scipy zpk → lp2bp → bilinear pipeline (not simplified formula)\n")
        output.write(" *   - peak_gain_correction = 1/|H(fc)| (always exactly 1.0 for scipy design)\n")
        output.write(" *   - biquad poles stay inside unit circle in float32 (stable)\n")
        output.write(" */\n\n")
        output.write("#pragma once\n\n")
        output.write("#include <cstdint>\n\n")
        output.write("namespace noise_toolkit {\n\n")
        output.write("struct BandpassCoeffs {\n")
        output.write("    float b0, b1, b2, a1, a2;  // a0 = 1.0 (normalized)\n")
        output.write("    float peak_gain_correction;  // 1.0 / |H(fc)|, applied at SPL level\n")
        output.write("};\n\n")
        output.write("constexpr BandpassCoeffs BANDPASS_COEFFS_48K[9] = {\n")

        for c in coeffs_list:
            output.write(
                f"    // Band {BAND_CENTER_FREQS.index(c['fc'])}: "
                f"{c['fc']:.0f} Hz ({c['fc']/BAND_FACTOR:.1f} - {c['fc']*BAND_FACTOR:.1f} Hz), "
                f"peak_gain={c['peak_gain']:.6e}, "
                f"correction={c['correction']:.6e}\n"
            )
            output.write(
                f"    {{ {c['b0']:.10e}f, {c['b1']:.10e}f, {c['b2']:.10e}f, "
                f"{c['a1']:.10e}f, {c['a2']:.10e}f, "
                f"{c['correction']:.10e}f }},\n"
            )

        output.write("};\n\n")
        output.write("} // namespace noise_toolkit\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output", "-o",
        type=Path,
        default=HEADER_PATH,
        help=f"输出头文件路径 (默认: {HEADER_PATH})"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="仅打印 sanity check，不写文件"
    )
    parser.add_argument(
        "--sample-rate",
        type=float,
        default=SAMPLE_RATE,
        help=f"采样率 (默认: {SAMPLE_RATE})"
    )
    args = parser.parse_args()

    fs = args.sample_rate

    print("=" * 78)
    print(f"v3.3.1 1/3 oct bandpass 系数重生成 (scipy.signal.butter, fs={fs})")
    print("=" * 78)
    print()
    print(f"{'频段':<8} {'b0':<14} {'b1':<14} {'b2':<14} {'a1':<14} {'a2':<14} {'|H(fc)|':<14} {'correction':<14}")
    print("-" * 110)

    coeffs_list = []
    for fc in BAND_CENTER_FREQS:
        c = generate_one_band(fc, fs=fs)
        coeffs_list.append(c)
        print(
            f"{fc:<8.0f} "
            f"{c['b0']:<14.6e} {c['b1']:<14.6e} {c['b2']:<14.6e} "
            f"{c['a1']:<14.6e} {c['a2']:<14.6e} "
            f"{c['peak_gain']:<14.6e} {c['correction']:<14.6e}"
        )

    print()
    print("=" * 78)
    print("Sanity check")
    print("=" * 78)

    # 验证所有 correction 都接近 1.0
    max_corr = max(c['correction'] for c in coeffs_list)
    min_corr = min(c['correction'] for c in coeffs_list)
    print(f"correction range: [{min_corr:.6f}, {max_corr:.6f}]")
    print(f"  期望: [0.95, 1.05] (scipy 标准设计应当一致)")
    if not (0.90 <= min_corr <= 1.10 and 0.90 <= max_corr <= 1.10):
        print(f"  ⚠️  WARNING: correction 偏离 1.0 较远")

    # 验证所有 b0 都 ≥ 1e-4（避免 v3.3.0 的 1e-7 极小值）
    min_b0 = min(c['b0'] for c in coeffs_list)
    print(f"min b0: {min_b0:.6e}")
    print(f"  期望: ≥ 1e-4 (避免 float32 精度边界)")
    if min_b0 < 1e-5:
        print(f"  ⚠️  WARNING: b0 过小，float32 精度可能不足")

    # 验证 a1/a2 接近 [-2, 1]（典型 Butterworth 带通特征）
    print()
    print("a1/a2 sanity (期望 a1≈-2, a2≈1):")
    for c in coeffs_list:
        print(f"  {c['fc']:.0f}Hz: a1={c['a1']:.6f}, a2={c['a2']:.6f}")

    # 验证极点稳定性
    print()
    print("极点稳定性 (期望 |poles| < 1.0):")
    for c in coeffs_list:
        # 二阶分母: 1 + a1·z^-1 + a2·z^-2 (a0=1)
        # 等价于 z^2 + a1·z + a2 = 0
        # 求根: z = (-a1 ± sqrt(a1^2 - 4·a2)) / 2
        disc = c['a1'] ** 2 - 4 * c['a2']
        if disc >= 0:
            z1 = (-c['a1'] + np.sqrt(disc)) / 2.0
            z2 = (-c['a1'] - np.sqrt(disc)) / 2.0
        else:
            z1 = complex(-c['a1'] / 2.0, np.sqrt(-disc) / 2.0)
            z2 = z1.conjugate()
        p1_abs = abs(z1)
        p2_abs = abs(z2)
        stable = p1_abs < 1.0 and p2_abs < 1.0
        flag = "✓" if stable else "✗"
        print(f"  {c['fc']:.0f}Hz: |p1|={p1_abs:.6f}, |p2|={p2_abs:.6f} {flag}")

    # 写文件
    if args.dry_run:
        print()
        print("=" * 78)
        print("Dry-run 模式: 未写文件")
        print("=" * 78)
        return 0

    output_path = args.output
    print()
    print("=" * 78)
    print(f"写入 {output_path}")
    print("=" * 78)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        emit_cpp_header(coeffs_list, f)

    print(f"✓ Done: {output_path} ({output_path.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())